[package]
name = "rdb"
version = "0.1.0"
authors = ["Spencer Powell <krornus@gmail.com>"]

[dependencies]
libc = "0.2"
nix = "0.9.0"
posix = "0.0.2"
spawn-ptrace = "0.1.0"
regex = "0.2.10"
twox-hash = "1.1.0"
memmap = "0.6.2"
vm-info = "0.1.0"
bitflags = "1.0"
twoway = "0.1.8"
